<a href="https://colab.research.google.com/github/deepakyadav043/Python_Library-Numpy/blob/main/class2file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [ ]:
import numpy as np
arr =[[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(arr)
#shape
print(arr.shape)

#ndim
print(arr.ndim)

#Size
print(arr.size)
#data type
print(arr.dtype)



(3, 3)
2
9
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [ ]:
arr = np.array([10,20,30,40,50])
#1d array ki indexing and slicing = List
print(arr[3])
print(arr[-1])

40
50


Now lets see the 2D indexing aswell

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1,2])
print(arr[0])
arr
arr[0:2,0:2]

6
[1 2 3]


array([[1, 2],
       [4, 5]])

In [ ]:
arr[0:2,0:2]#Rows from 0 & 1 and colums

array([[1, 2],
       [4, 5]])

In [ ]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

Now we can also do the slicing lets see the **slicing in 1D**

In [ ]:
arr[1:,1:2]

array([[5],
       [8]])

1D slicing was really easy now lets see the **slicing in 2D**

There is one more thing known as **Boolean indexing**

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr>5)
print(arr[arr > 5])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


In [ ]:
import numpy as np
arr = np.arr([[1,2,3],[4,5,6],[7,8,9]])

print(arr[1,2])
print(arr[0:2])
# arr
# arr[0:2,0:2]


AttributeError: module 'numpy' has no attribute 'arr'

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [ ]:
#when we have to convert an 1 D array into an
#2D array we use .reshape(row,column)
import numpy as np
arr = np.arange(12)
arr
reshaped = arr.reshape(6,2)
reshaped


## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [ ]:
#And .flatten() will convert and 2D into an 1D array
arr = np.array ([[1,2,3],[4,5,6],[7,8,9]])
oneD = arr.flatten()
oneD

In [ ]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

#1 Addition of the array
print(a+b)

#subtracting of the array
print(a-b)

#

In [ ]:
a = np.array([10,20,30,40,50])
print(a*5)

In [ ]:
import numpy as np
A = np.array([[10,20,30],
             [40,50,60]])
B = np.array([10,20,30])

print(A+B)

In [ ]:
#Aggegration function
#Basic Statical operation perform
from numpy import *

arr = array([10, 20, 30, 40, 50])
#1.sum

print(f"Sum is: {arr.sum}")

#2.mean
print(f"Mean(Average) is :{arr.mean()}")

#3.min
print(f"Min is : {arr.min()}")
#4.max
print(f"Max is :{arr.max()}")

#5.standard variation
print(f"Standard Deviation:{arr.std()}")

#6.variance
print(f"Variance:{arr.var()}")



In [ ]:
import numpy as np
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(f'sum of all:{data.sum()}')
#axis = 0 --> columns
#axis = 1 --> rows
print(f'sum of columns: {np.sum(data,axis= 0)}')
print(f'sum of rows:{np.sum(data,axis = 1)}')

In [ ]:
##Axis

