<a href="https://colab.research.google.com/github/deepakyadav043/Python_Library-Numpy/blob/main/class3file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [ ]:
import numpy as np

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

#1 Addition of the array
print(a+b)

#subtracting of the array
print(a-b)

#

[11 22 33 44]
[ 9 18 27 36]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [ ]:
a = np.array([10,20,30,40,50])
print(a*5)

[ 50 100 150 200 250]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [ ]:
import numpy as np
A = np.array([[10,20,30],
             [40,50,60]])
B = np.array([10,20,30])

print(A+B)

[[20 40 60]
 [50 70 90]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [ ]:
#Aggegration function
#Basic Statical operation perform
from numpy import *

arr = array([10, 20, 30, 40, 50])
#1.sum

print(f"Sum is: {arr.sum()}")

#2.mean
print(f"Mean(Average) is :{arr.mean()}")

#3.min
print(f"Min is : {arr.min()}")
#4.max
print(f"Max is :{arr.max()}")

#5.standard variation
print(f"Standard Deviation:{arr.std()}")

#6.variance
print(f"Variance:{arr.var()}")



Sum is: 150
Mean(Average) is :30.0
Min is : 10
Max is :50
Standard Deviation:14.142135623730951
Variance:200.0


You can also do the axis based operations row-Wise and Colum-wise

In [ ]:
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(f'sum of all:{data.sum()}')
#axis = 0 --> columns
#axis = 1 --> rows
print(f'sum of columns: {np.sum(data,axis= 0)}')
print(f'sum of rows:{np.sum(data,axis = 1)}')

sum of all:45
sum of columns: [12 15 18]
sum of rows:[ 6 15 24]
