<a href="https://colab.research.google.com/github/deepakyadav043/Python_Library-Numpy/blob/main/Class1file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
pip install numpy


Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
import numpy as np
l = [10,20,30,40,50] #1D array
array = np.array(l)
print(array)


[10 20 30 40 50]


Lets create a matrix using list

In [ ]:
a = [[1,2,3],
 [4,5,6],
  [7,8,9]]
matrix = np.array(a)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now lets see how matlix looks like using numpy arrays

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
#np.zeros()
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#np.zeros() for matrix
#rows and columns
np.zeros([3,4])#rows,colums


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.ones()
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
#np.ones() for matrix
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#np.full()
np.full(20,45)

array([45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
       45, 45, 45])

In [ ]:
#np.full() for matrix
np.full([3,4],8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [ ]:
#np.arange()
arr = np.arange(0,10,3)
arr

array([0, 3, 6, 9])

In [ ]:
#np.eye() #Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#np.linspace() # start = 0 ,stop = 1,value = 5

np.linspace(0,1,7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [ ]:
#np.random.rand() #rows,#columns
np.random.rand(4,6)

array([[0.57663732, 0.83020881, 0.30145299, 0.47150778, 0.40627185,
        0.27561075],
       [0.13899681, 0.26888992, 0.05930285, 0.2787146 , 0.1862354 ,
        0.87508197],
       [0.85757023, 0.21947545, 0.10024513, 0.95233848, 0.16396751,
        0.67547569],
       [0.24084277, 0.75118106, 0.17799086, 0.76159754, 0.91305977,
        0.96585467]])

In [ ]:
#np.random.randint(start,stop,(rows,columns))
np.random.randint(1,20,(3,3))
"""
randint-->> 1 se 20 ke beech ki random value se matrix create hoga"""

'\nrandint-->> 1 se 20 ke beech ki random value se matrix create hoga'

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution