<a href="https://colab.research.google.com/github/deepakyadav043/Python_Library-Numpy/blob/main/numpy_final_assign.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Final NumPy Assignment
# Inputs khud se create karna hai



# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
import numpy as np
arr = [10,20,30,40,50]
arr = np.array(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(5,)
1
5
int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(arr)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[3])
print(arr[-1])

1
4
6



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:5])

[3 4 5]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr = np.array([10,20,30,40,50,60])
arr[[0,2,4]]

array([10, 30, 50])


# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr = np.array([10,20,30,40,50])
np.where(arr>15)
print(arr[arr>15])

[20 30 40 50]



# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr = np.array([10,20,30,40,50])
print(arr+10)

[20 30 40 50 60]



# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr = np.array([10,20,30,40,50,60])
#1 Sum
print(f"sum is {arr.sum()}")
#2mean
print(f"mean(average) is{arr.mean()}")
#3 max
print(f"max is :{arr.max()}")
#4min
print(f"min is :{arr.min()}")

sum is 210
mean(average) is35.0
max is :60
min is :10



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
array = np.array([50,40,90,60,80,30])
print(np.sort(array))

index = np.argsort(array)
print(index)


[30 40 50 60 80 90]
[5 1 0 3 4 2]



# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate([a,b])
np.vstack([a,b])


array([[1, 2, 3],
       [4, 5, 6]])