<a href="https://colab.research.google.com/github/deepakyadav043/Python_Library-Numpy/blob/main/Numpy_Matrix_Pandas_Assignment_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Matrix + Pandas Assignment


## Q1. Create a 3×3 NumPy Matrix

### Input
```
1 2 3
4 5 6
7 8 9
```

### Output
```python
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```


In [ ]:
import numpy as np
arr = ([[1,2,3],[4,5,6],[7,8,9]])
arr = np.array(arr)

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Q2. Multiply Matrix by 2

### Input
```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

### Output
```python
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
```


In [ ]:
import numpy as np
arr = ([[1,2,3],[4,5,6],[7,8,9]])
arr = np.array(arr)

print(arr*2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Q3. Find Row-wise Sum

### Output
```python
[ 6 15 24]
```


In [ ]:
print(arr.sum(axis = 1))

[ 6 15 24]


## Q4. Find Column-wise Sum

### Output
```python
[12 15 18]
```


In [ ]:
print(arr.sum(axis = 0))

[12 15 18]


## Q5. Extract Second Row

### Output
```python
[4 5 6]
```


In [ ]:
print(arr[1])

[4 5 6]


## Q6. Create DataFrame

| Name | Marks |
|------|------|
| Raj | 80 |
| Amit | 70 |
| Neha | 90 |
| Priya | 85 |


In [ ]:
import pandas as pd

info = pd.DataFrame({
    'Name':["Raj","Amit","Neha","Priya"],
    'Marks':[80,70,90,85]
})
print(info)

    Name  Marks
0    Raj     80
1   Amit     70
2   Neha     90
3  Priya     85


## Q7. Add Bonus Column

Bonus = Marks + 5

### Expected Output
```
Raj    80   85
Amit   70   75
Neha   90   95
Priya  85   90
```


In [ ]:
import pandas as pd

info = pd.DataFrame({
    'Name':["Raj","Amit","Neha","Priya"],
    'Marks':[80,70,90,85]
})
info['Bonus_Marks'] = info['Marks'] + 5
print(info)

    Name  Marks  Bonus_Marks
0    Raj     80           85
1   Amit     70           75
2   Neha     90           95
3  Priya     85           90


## Q8. Display Students Having Marks > 80

### Expected Output
```
Neha   90
Priya  85
```


In [ ]:
info[info['Marks']>80]

,Name,Marks
2,Neha,90
3,Priya,85


## Q9. Print First Row Using iloc

### Expected Output
```
Raj 80
```


In [ ]:
print(info.loc[0])

Name     Raj
Marks     80
Name: 0, dtype: object


## Q10. Print Third Row Using iloc

### Expected Output
```
Neha 90
```


In [ ]:
print(info.loc[2])

Name     Neha
Marks      90
Name: 2, dtype: object


## Q11. Print First 2 Rows Using iloc

### Expected Output
```
Raj 80
Amit 70
```


In [ ]:
print(info.loc[0:1])

   Name  Marks
0   Raj     80
1  Amit     70


## Q12. Print Only Name Column Using iloc

### Expected Output
```
Raj
Amit
Neha
Priya
```


In [ ]:
print(info.loc[])

## Q13. Update Amit's Marks to 75

### Expected Output
```
Amit 75
```


In [ ]:
# Write your code here

## Q14. Sort DataFrame by Marks (Descending)

### Expected Output
```
Neha  90
Priya 85
Raj   80
Amit  75
```


In [ ]:
# Write your code here